openapi: 3.0.3
info: 
  title: Eazyshop Products APIs Definition
  version: 0.0.1
servers:
- url: http://www.traveltech.ro/alpha/api/v1
paths: 
  /cateogries:
    get:
      summary: List all categories
      description: Returns the list of categories supported by Eazyshop
      parameters:
      - name: categoryId
        in: query
        schema:
          type: integer
          minimum: 100
          maximum: 1000
        example: 101
      responses:
        '200':
          description: A list of categories
          content:
            application/json:
              schema:
                type: array
                items: 
                  type: object
                  properties:
                    categoryId:
                      type: integer
                    name:
                      type: string
  /cateogries/{categoryId}:
    get:
      summary: Category by id
      description: Returns product details
      parameters:
      - name: categoryId
        in: path
        required: true
        schema:
          type: integer
          minimum: 100
          maximum: 1000
        example: 101
      responses:
        '200':
          description: A list of categories
          content:
            application/json:
              schema:
                type: object
                properties:
                  categoryId:
                    type: integer
                  name:
                    type: string
  /products:
    get:
      summary: List all product
      description: Returns the list of products supported by Eazyshop
      parameters:
      - name: productId
        in: query
        schema:
          type: integer
          minimum: 100
          maximum: 1000
        example: 101
      responses:
        '200':
          description: A list of products
          content:
            application/json:
              schema:
                type: array
                items: 
                  type: object
                  properties:
                    productId:
                      type: integer
                    name:
                      type: string
                    price:
                      type: number
                    categoryName:
                      type: string
                    quantity:
                      type: integer
  /products/{productId}:
    get:
      summary: Category by id
      description: Returns the a product by Eazyshop
      parameters:
      - name: productId
        in: path
        required: true
        schema:
          type: integer
          minimum: 100
          maximum: 1000
        example: 101
      responses:
        '200':
          description: product details
          content:
            application/json:
              schema:
                type: object
                properties:
                  productId:
                    type: integer
                  name:
                    type: string
                  price:
                    type: number
                  categoryName:
                    type: string
                  quantity:
                    type: integer
  /orders:
    post:
      summary: Create order
      description: |
        Create order details to EazyShop for processing
        and shipping
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                products:
                  type: array
                  items: 
                    type: object
                    properties:
                      productId:
                        type: integer
                      name:
                        type: string
                      price:
                        type: number
                      categoryName:
                        type: string
                      quantity:
                        type: integer
                address:
                  type: object
                  properties:
                    addressLine:
                      type: string
                    city:
                      type: string
                    state: 
                      type: string
                    zipcode:
                      type: string
      responses:
        '201':
          description: Order created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  orerId:
                    type: integer
    put:
      summary: Create order
      description: |
        Update order details to EazyShop for processing
        and shipping
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                orderId:
                  type: integer
                products:
                  type: array
                  items: 
                    type: object
                    properties:
                      productId:
                        type: integer
                      name:
                        type: string
                      price:
                        type: number
                      categoryName:
                        type: string
                      quantity:
                        type: integer
                address:
                  type: object
                  properties:
                    addressLine:
                      type: string
                    city:
                      type: string
                    state: 
                      type: string
                    zipcode:
                      type: string
      responses:
        '200':
          description: Order details updated successfully
    delete:
      summary: Delete Order
      description: Delete order details from EazyShop
      parameters:
        - name: orderId
          in: query
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Order details cancelled successfully
    get:
      summary: Get Order details
      description: Returns the list of orders placed at Eazyshop
      parameters:
        - name: orderId
          in: query
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A list of orders
          content:
            application/json:
              schema:
                type: object
                properties:
                  orderId:
                    type: integer
                  products:
                    type: array
                    items: 
                      type: object
                      properties:
                        productId:
                          type: integer
                        name:
                          type: string
                        price:
                          type: number
                        categoryName:
                          type: string
                        quantity:
                          type: integer
                  address:
                    type: object
                    properties:
                      addressLine:
                        type: string
                      city:
                        type: string
                      state: 
                        type: string
                      zipcode:
                        type: string
        