openapi: 3.0.3
info: 
  title: Starwars APIs Definition
  version: 0.0.1
servers:
- url: https://swapi.online/api
paths:
  /films:
    get:
      summary: List of starwars filsm
      description: List all starwars films on filming order
      responses:
        '200':
          description: Starwars films
          content:
            application/json: 
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    producer:
                      type: string
                    title:
                      type: string
                    episode_id:
                      type: integer
                    director:
                      type: string
                    release:
                      type: string
                      format: date
                    opening_crawl:
                      type: string
